spring:
  application:
    name: core-banking-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: Welcome@#123!
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 9095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka

info:
  app:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
